### ISSUE TITLE
Candidate partner re-assignment from Settings > System Admin API

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1215]
As a system admin
I would like to be able to reassign a candidate's partner directly from the TC
Instead of raising it as a support request for the engineering team to do it in the database
Because it is more efficient to be able to do it directly when needed.

---
Request from Zeynep. 

A side benefit is that changing this information directly from the TC means that a full Redis cache flush will not be required.

SS update: and see below, will also address ES index going out of sync

**Comment by samschlicht** [comment]
We've expedited this since it's become evident that direct DB edits of candidates/users are particularly problematic because:

- They bypass our Redis cache evictions
- They don't update the corresponding candidate entry in the elasticsearch index

Discussed w Sadat is to implement a System Admin Api method that takes a partner id and list id, reassigning all the candidates on the list to the partner with the given ID.
