### ISSUE TITLE
Java ChatPost entity setLinkPreviews throws null pointer exception

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1245]
setLinkPreviews method needs to handle being passed a null value.

It also doesn't clear existing linkPreviews - so they will accumulate.

**Comment by samschlicht** [comment]
@camerojo I found this one earlier this week and addressed it [here](https://github.com/Talent-Catalog/talentcatalog/pull/1236/files#diff-65f26c75b24531f5477e197c9779d60718f99b614d615062de16fefa6e1bef1d) - but that one hasn't been merged yet. Would you mind taking a look there. I opted to initiate an empty list but perhaps you'd advise a null check on the setter instead (or as well as)?

What do you mean by clearing link previews? I do save the scraped version in the DB so that if someone were to load a Chat thread with a lot of links in, then they're not scraping a dozen or more links at once, which would be messy UX - that seems to be the way the big services do it.

**Comment by camerojo** [comment]
This is a different bug @samschlicht .

The bug is in the ChatPost entity, not Post.

<pre>
  public void setLinkPreviews(List<LinkPreview> linkPreviews) {
         //TODO JC This still has problems because it doesn't clear out existing linkPreviews
         if (linkPreviews != null) {
             linkPreviews.forEach(linkPreview -> {
                 linkPreview.setChatPost(this);
                 this.linkPreviews.add(linkPreview);
             });
         }
     } 
</pre>

I put the null check in just so that I could get my test working.

Note that there are two objects called "linkPreviews" - one is the property of ChatPost and the other is the parameter to the setLinkPreviews method. The parameter can be null (in fact was in the test I was trying to run) - without the added check, it crashes.

Also, in the set method, nothing removes the existing content of the linkPreviews property. So if there 2 link previews and the set method is called 10 times, you will end up with 20 link previews in the linkPreviews collection - 10 duplicates of the 2 actual link previews.

**Comment by samschlicht** [comment]
@camerojo by initialising an empty list in Post, which as I understand it is always the precursor for a ChatPost, the setLinkPreviews method in ChatPost doesn't throw a null pointer exception. But I suppose the null check is still worth having in case we change the way that Chat Posts are created. Sounds like you've included that in your PR, so that's great.

On the second point, why would the set method be called 10 times? It's called once per post. I'm testing it now and 3 link previews in a Post = three saved link previews in the link_preview DB table and on the corresponding Chat Post.

Am I missing something about the way the Chat Posts are created?

**Comment by samschlicht** [comment]
Read JC description:
https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1723154657700979?thread_ts=1723008663.987269&cid=C0583HJ9CHM

**Comment by camerojo** [comment]
Hey @samschlicht - once you have had a chance too read through the above doc I referred you to, I think you may not need that setLinkPreviews at all. In fact, I don't think you need to pass the linkPreviews down in the in Post request - because they are updated in their own calls to the LinkPreviewAdminAPI.

**Comment by samschlicht** [comment]
Here's the article for quick ref: https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/

That's how I'll define the relationship between the entities — makes total sense to me now!
