### ISSUE TITLE
No icon for watching search in Saved Search display

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1421]
Icon only appears in search selection screen selected search summary

**Comment by cazcam34** [comment]
Added the watched icon. Also noticed as we are now displaying the new header component (instead of breadcrumb) for sources, that the icons for default searches can probably be reduced. I propose we get rid of the 'open in new tab' button, the starred button, the associate task with list button, and even the search id number.
<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9OQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06dc7a0e6d8ca5950cc7ba3bb94959cfde067683/Screen%20Shot%202024-09-30%20at%203.59.18%20pm.png" alt="Screen Shot 2024-09-30 at 3.59.18 pm.png" />

What i propose:
<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBOQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d96d648b9fbd8e12f2fd809f0620ef10b656c23d/Screen%20Shot%202024-09-30%20at%204.08.48%20pm.png" alt="Screen Shot 2024-09-30 at 4.08.48 pm.png" />
