### ISSUE TITLE
Add intake info to search 

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#157]
As an admin user
I would like to be able to filter my search by intake status (e.g. like the opps filter)
And also by mini and full intake dates
So that I can quickly select candidates who have completed intake stages

**Comment by sadatmalik** [comment]
Copied from Trello issue after discussion with Zeynep & Mariam:

"For sorting purposes probably do need candidate fields intakeMini and intakeFull to easily identify which candidates are intaked.

New candidate fields

intakeMini date
intakeFull date"

**Comment by tbbadmin** [comment]
See:
https://docs.google.com/spreadsheets/d/1ratxVXHpfhCG46V3wIg1z07UeIS0z3sAdWk8sHJW8AE/edit#gid=0

**Comment by samschlicht** [comment]
- [ ] #156 - This is basically the same issue and easy to do at the same time

**Comment by samschlicht** [comment]
Zeynep to get back to Mariam re incl mini intake - space is at a premium so might not be necessary

**Comment by samschlicht** [comment]
- Mariam and Nourhan view both mini and full intake as useful and deserving to be on the table as columns — they’re important for seeing more precisely how much work is left to do on a given submission list or search. 
- Mariam suggested the possibility of icons indicating mini-intaked OR fully-intaked, rather than columns - could be 1 or 2 out of 2 (like with tasks). 
- They both 
- felt that dates don’t necessarily need to be displayed except for being accessible in the candidate notes in the sidebar, which they already are. 
- Candidate search filter could search only by Mini Intake or Full Intake (understanding that searching by dates will later be included in a separate intake stats section)
- Hovering over the intake icon to reveal the date it was done would be a good value-add.

**Comment by samschlicht** [comment]
From Zeynep:
This all sounds good to me! Maybe I’d like to push back on the icon a bit. Again, it’s so typical for people to do both at the same time so candidates who are at 1 out of 2 will be rare and I think 2/2 will be confusing for partners who consider it a single process. But I do agree they can be on the same column! Just would prefer it to be in writing if possible. Can we maybe call the column intake status with options: not completed, mini-intake, full-intake?

**Comment by samschlicht** [comment]
Note to review intake functionality: buttons, legacy functionality

**Comment by samschlicht** [comment]
Take a look at spec file and speak to Sadat monday

**Comment by samschlicht** [comment]
TODO: make sure this isn't a sortable column
Remove @nullable from getIntaked()
Can getTitle ever return null? Is it nullable already? If it could be null, needs an escape

**Comment by samschlicht** [comment]
Split this issue when done, creating a new ticket for the rest of it

**Comment by samschlicht** [comment]
Noted in my pull request but will add here: in consultation on this issue, Mariam and Zeynep expressed that seeing at a glance which candidates are intaked (on candidate search and submission lists) would be useful as a standalone feature, so I'm splitting this ticket — will create a new one for the search filter, which is probably more important but may unfortunately have to wait till next release...

**Comment by samschlicht** [comment]
Also just noting here my comment on my final commit:, addressing issues discussed in team meeting: 
- getIntaked() no longer annotated @nullable (it never returns null)
- getTitle() cannot return null, so there's no need for an escape clause
- introduced frontend functionality to deal with sortable/unsortable fields, thereby preempting the error that clicking to sort a @transient field would otherwise produce
