### ISSUE TITLE
Sync TC candidate dependants with SF [Linking family size information from TC intakes to SF candidate opportunities]

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#161]
SF can have dependants (synced from TC) and dependants relocating. If dependants relocating is blank, it can default from dependants.

That way, updating from TC will only overwrite dependents on SF. Dependants relocating can be updated manually (eg removing some dependants who are not actually going to relocate)

See https://refugeejobsmarket.slack.com/archives/C7QK72T4J/p1647914873328889?thread_ts=1647764457.197539&cid=C7QK72T4J

**Comment by sadatmalik** [comment]
Migrated from Trello following discussion with Zeynep.

Duplicate Trello tickets:
- Link dependants gender field to salesforce to calculate relocation information for dependents
- Linking family size from TC to people moves report on SF. Will need: Relocating men, Relocating women, Relocating boys, Relocating girls

**Comment by tbbadmin** [comment]
- [x] #148

**Comment by samschlicht** [comment]
**Draft plan**
Will test this in TC Staging-SF Sandbox before making any changes to SF Prod - noting slight concern re object limit on partial-copy sandboxes, which is 10,000 per object. I'm thinking I'll only sync the first 5,000 from TC Staging, so there'll need to be a bit of if logic to deal with that. Judging by some online comments, hitting that upper limit can make the sandbox do some strange things that I'd rather not have to deal with.

 Add desired to fields to SF SANDBOX contact records, which Sarah, Zeynep and I compiled in this doc (will add link to this as soon as I find it!) - including the new email consent fields that Caroline has added.
-[ ] Amend ContactRequest nested class in SalesforceService to include these fields
-[ ]  Make a @Scheduled method in SalesforceService using SalesforceService.createOrUpdateCandidates, passing an ordered list of all live candidates on DB, incl. also the method from CandidateOpportunityService.createUpdateCandidateOpportunities to update the SF link for all of them (which is why the list needs to be ordered) (Q - is it a problem to do this for all candidates every time? I'm thinking we will need to update existing SF records, so I don't know what the alternative would be)
-[ ] After merge, check that it's working on TC Staging and SF Sandbox and, if so, replicate the object changes on SF prod ready for the next release (or is there a way to check an @Scheduled method from dev?)
I'm reasoning that I don't need to change other candidate-creating methods, e.g., when someone hits the 'update/create SF' button on a candidate, or when someone creates a candidate opportunity for a candidate who isn't on SF yet: because this is a scheduled task, and not happening all the time, it's very possible that someone could execute one of those methods BEFORE a candidate has been added to SF - so we still need to check whether the candidate exists on SF yet, and create them if necessary.

**Comment by samschlicht** [comment]
Just noting that this one is blocked on #416 — no point setting up a sync while changes pending to underlying data.

**Comment by samschlicht** [comment]
Just summarising this one for my own clarification:

- TC captures dependant info at intake and this is currently being manually logged on SF to inform our reporting
- We would like it to be synced
- But also, sometimes not all candidates' dependants relocate — this is sometimes captured by TC visa assessment (only CA at the moment), in which case we would like to sync that info to SF _when we have it_, overriding the existing dependant info.

Noting also that Ajay set up [an SF Flow](https://talentbeyondboundaries.lightning.force.com/builder_platform_interaction/flowBuilder.app?flowId=3013l000000Gh8uAAC) that sets the Dependants Relocated Date to the current date when the Dependants Relocated checkbox is checked. I don't see any conflict there for now, but just something to bear in mind.

**Comment by samschlicht** [comment]
This info is already in the 'job-specific' section of the visa assessment, so it should be quite straightforward to link it appropriately.

**Comment by samschlicht** [comment]
This section of the visa assessment is already linked to a specific job, so this should be quite a straightforward update step, notwithstanding that the dependants are a string of IDs.

**Comment by samschlicht** [comment]
Rough running order here:
- [ ] when candidate opportunities are created/updated, sync dependant info from TC candidate intake to SF candidate opportunity 
- [ ] when a candidate visa job check is created/updated, override SF candidate opportunity 'Relocation Information'
- [ ] ensure that the latter continues to take precedence, irrespective of subsequent changes

**Comment by samschlicht** [comment]
Granular: when candidate opportunities are created/updated, sync dependant info from TC candidate intake to SF candidate opportunity
- [ ] update CandidateOpportunityRequest to set Relocating Information fields on SF
- [ ] add method to calculate those fields to SalesforceServiceImpl.createOrUpdateCandidateOpportunities - taking a string of IDs and returning a map of strings and corresponding longs

**Comment by cazcam34** [comment]
As discussed two related new issues, as there are two destinations that are missing the 'relocating dependants' field on the visa check. UK missing the entire visa check on the TC (#646) & AU which is just missing the question (#647). When they are completed we can rollout the solution to those other destinations.

**Comment by samschlicht** [comment]
Had a good chat with John and Caroline, which has led to a change in direction that makes sense to me. 

To summarise: 
- While it might seem expedient to sync SF candidate opportunity relocating dependents with the info recorded at TC intake, it will still lead to inaccurate data and manual revision. (Families change, different visa pathways and employers offer different possibilities.)
- The sustainable solution is to update SF from the job-specific candidate visa assessments, which in (only) Canada's case includes a section for this purpose:

<img width="931" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8eb9584cb8cdeb6d6c6a84643506b128aeb40d83/Screenshot%202024-02-12%20at%202.28.03%E2%80%AFpm.png" alt="Screenshot 2024-02-12 at 2.28.03 pm.png" />

**Comment by samschlicht** [comment]
What we propose instead is to add a button to that section of the visa assessment to update the case relocation information. Additionally we may auto-update at key opportunity stages.

Australia's visa assessment will need a section like Canada's 'Family Assessment' (moving ahead as #647), and the UK need to move ahead with getting one in place (#646).

I'll get in touch with Zeynep, who's probably the main stakeholder here, and explain the change in direction. The ask here is quite similar, so I'll stick with this issue to get the new solution in place.

**Comment by samschlicht** [comment]
- [ ] add an 'Update Case' button (we'll review the wording as it's a bit tricky — we don't want to mention SF but that's the main purpose really!)
- [ ] Code method to process string of dependant IDs recorded at visa assessment and supply to case update/create
- [ ] invoke this method at key stage change

**Comment by samschlicht** [comment]
[Slack post tagging Zeynep in the original thread for this issue](https://refugeejobsmarket.slack.com/archives/C7QK72T4J/p1707710122119559?thread_ts=1647764457.197539&cid=C7QK72T4J)

**Comment by samschlicht** [comment]
Just noting that I don't think auto-updating at a certain stage is necessarily the way to go here — it seems like it ought to be a deliberate step (i.e., just the button), since the count can still be updated directly on SF. And that does need to be possible since, at present at least, many opportunities won't use the visa assessment tool. Not to mention that not all of our staff will know to return to the visa assessment tool if they want to change the relocating count.

**Comment by samschlicht** [comment]
To summarise, we've settled on the following approach for this issue:

- Added a button to update relocation information from the CA visa assessment tab and we've logged separate issues to be able to do the same for other countries (#647, #646) and from a tab on TC cases in general (#651).
- The last step is to get team sign-off on the button wording and appearance:
<img width="1854" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8b1b731a25241ce353bb445659903deab470235/Screenshot%202024-02-19%20at%203.43.43%E2%80%AFpm.png" alt="Screenshot 2024-02-19 at 3.43.43 pm.png" />
<img width="1562" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDVyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7306d9427f7c7d01bcae568615277cf8d6af7e0/Screenshot%202024-02-19%20at%203.44.57%E2%80%AFpm.png" alt="Screenshot 2024-02-19 at 3.44.57 pm.png" />
