### ISSUE TITLE
Bug: user's own chat reactions not appearing until refresh

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#1642]
Apologies for my son's shouting in the background!

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3kvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd68aa958cbd17444cca82636993a8535762da25/Screen%20sharing%20-%202024-11-15%208_56_10%20AM.mp4)

There could be more to this but I have to move on to another task and haven't checked yet — I suggest that whoever picks this up should give reactions in general a thorough test. 👍

**Comment by EhsanEhrari** [comment]
After checking and investigating this issue, I found that the route **_/api/admin/reaction/{chatPostId}/add-reaction_** and the methods **public void addReaction** and **public void modifyReaction** are working correctly on the backend. However, the issue arises because they are not sending any data back to the frontend, causing the updatedReaction object in the frontend to be null. To resolve this, we need to ensure that the backend sends the updated list of reactions in the response, so that the frontend can properly update the UI with the latest reaction data.

**Comment by EhsanEhrari** [comment]
It was the same issue on the candidate portal as well. After further investigation, I found that inside the **handleIncomingPost** method of **PostsComponentBase**, the **groupedMessages** array was not being updated when a post was modified. Adding the following line resolved the issue:

`this.groupedMessages = this.groupMessagesByDate(this.posts);
`
This ensures the groupedMessages are updated correctly when posts are modified.
