### ISSUE TITLE
In submission lists, the context portion of the side panel display can show the case's progress: ie stage, next step and next step due date

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#221]
As a partner reviewing candidate cases in a submission list
I would like to be able to easily see and modify the progress of the selected case in the right hand panel

**Comment by cazcam34** [comment]
Not sure if this already completed... We currently have the candidate opps stage viewable under the Jobs tab. Its also editable upon candidate selection in the submission list.

<img width="762" alt="Screen Shot 2023-10-02 at 3 17 30 pm" src="https://github.com/Talent-Catalog/talentcatalog/assets/43192228/d2aa3091-5fcb-48d2-beb1-f2511b9b5f63">

**Comment by cazcam34** [comment]
Alternatively I have put together an option in the side panel. But I think it might be unnecesssary and issue fixed with the previously completed jobs tab as above.

<img width="773" alt="Screen Shot 2023-10-02 at 3 21 33 pm" src="https://github.com/Talent-Catalog/talentcatalog/assets/43192228/bc98398a-c329-4ef1-8af3-e0024dbdfd57">
