### ISSUE TITLE
Bug: Mismatch between search results and stats

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#388]
From Lea:

https://tctalent.org/admin-portal/infographics/search/2575

As you can see in the first snapshot the total number retrieved from the search is 820, however when I run the stats (screenshot 1, 2, and 3) the total number is way less than 820. It seems like the stats are not running for all candidates.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1698245892994139?thread_ts=1698245892.994139&cid=C42S4AJ73)

Notes:

Look at the combination of search criteria. This is quite a complex search including elastic search + status + location. Look in this area to reproduce the issue locally.

**Comment by sadatmalik** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1Z6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcf920b4c236c6641a90fca218284021b6c3a662/image%20%281%29.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2R6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58b617b0b0a8dc49cb95d9e33cfc3b26df41938d/image%20%283%29.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2x6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9bb78d872cdd354ebc78204989562c439a07ba1/image%20%284%29.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3B6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33b606a23d6553f5faff8ae868aed86890198c7e/image%20%285%29.png)

**Comment by sadatmalik** [comment]
Call with Lea and Mariam:

Lea confirms that this mismatch happens for elastic searches only.

**Comment by sadatmalik** [comment]
Testing:

Check that the exported sheet displays the correct numbers (i.e. matches the searched list results)

**Comment by samschlicht** [comment]
First of all, just confirming that I can reproduce this locally: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2kzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8570363e0e7d88f230503c878cc8dff06609053c/Screenshot%202024-01-11%20at%2012.03.27%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 12.03.27 pm.png" />

<img width="978" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL20zQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e320d9672d007dab0fb44b8e744131a7ac35cd68/Screenshot%202024-01-11%20at%2012.04.12%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 12.04.12 pm.png" />

**Comment by samschlicht** [comment]
To answer Sadat's Q above, the exported search sheet does match the search's candidate number, and the exported stats sheet matches the search stats number.

**Comment by samschlicht** [comment]
So, in my version of Lea's search, I'm losing 9 candidates. As one might expect, this is happening in the elasticsearch section of the searchCandidates method in SavedSearchServiceImpl.

The elasticsearchOperations.search() method used here is returning 19 'totalHits', but the method is returning the 10 'searchHits' — so that's what I need to figure out.

<img width="441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTI0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcc4f2fa11163b0e3d5201d0c6612ba2e3df33ee/Screenshot%202024-01-11%20at%202.09.57%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 2.09.57 pm.png" />

**Comment by samschlicht** [comment]
- Stat search uses this search method: `@NotNull Set<Long> searchCandidates(long savedSearchId)`
- Regular search uses this one: `Page<Candidate> doSearchCandidates(SearchCandidateRequest request)`

I'm guessing they'll differ in their use of elasticsearch.

**Comment by samschlicht** [comment]
It looks like Lea's stats page also had 10 candidates, despite the actual search returning 820 or so result. Interesting that mine also produced 10 (instead of 19 using my dev DB), particularly in light of this diff I found between searchRequests:

<img width="1798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFM0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da7bc8bf13a5e840abd52ab628c11819280ddad6/Screenshot%202024-01-11%20at%202.55.39%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 2.55.39 pm.png" />

This seems to be caused by an erroneous pageable request that's being interjected by the NativeSearchQueryBuilder:

<img width="608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFc0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7100b960fd5d3842c28068ffcd43b94d32cd4338/Screenshot%202024-01-11%20at%203.11.35%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 3.11.35 pm.png" />

The stats request is submitting a page size, which is null — wondering if some kind of fallback default is being applied by the NativeSearchQueryBuilder.

**Comment by samschlicht** [comment]
This, from [the Spring elasticsearch doc](https://docs.spring.io/spring-data/elasticsearch/docs/5.1.7/reference/html/) appears to be the root of the issue:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCs0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bcaa86bb9681804e81ff8253cddcb3627264280/Screenshot%202024-01-11%20at%203.49.53%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 3.49.53 pm.png" />

And here's the offending line of code! (DEFAULT_PAGE is 10):

<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU80QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6d9a85f673868e5474c9bcfb8c0cfd68747a868/Screenshot%202024-01-11%20at%203.58.55%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 3.58.55 pm.png" />

**Comment by samschlicht** [comment]
So here's the fix:

- We setPageable with an instance of Pageable representing no pagination:

<img width="468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWE0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdca7662751b4f1cc06b234a454fe4561e384ccb/Screenshot%202024-01-11%20at%204.00.26%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 4.00.26 pm.png" />

Our query now contains this instead of `pageNumber = 10`:

<img width="340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWU0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--444b3c5e9c6625b737ff72e4392524ff56d65f5f/Screenshot%202024-01-11%20at%204.03.28%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 4.03.28 pm.png" />

And we get our 19 candidates!:

<img width="1006" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW00QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1aaeb05d04599006646ddf4783e83e66b78a1111/Screenshot%202024-01-11%20at%204.04.24%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 4.04.24 pm.png" />

**Comment by samschlicht** [comment]
The only other method using this one is isEmpty(), which is ultimately used only to check whether a submission list is empty and thereby set a boolean. Since it doesn't display the results, I don't see an issue with the response being unpaged. But I'll manually test it just in case.

<img width="653" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkM0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cda987b1a4831e57311021aafc1155e373356f51/Screenshot%202024-01-11%20at%204.11.00%E2%80%AFpm.png" alt="Screenshot 2024-01-11 at 4.11.00 pm.png" />

**Comment by samschlicht** [comment]
Yep, still working fine. Will do a couple more manual tests of the bug and then push.

**Comment by samschlicht** [comment]
Final Q: have we done anything with the other 2 requests in [Lea's Slack message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1698245892994139)? I can't find them noted as other issues...

**Comment by sadatmalik** [comment]
Great stuff @samschlicht !
