### ISSUE TITLE
Base search does not work with Elasticsearch.

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#454]
Note that fixing this bug is probably the easiest way to solve issue #248

You would create a Base search for TBB operations countries. Then any search containing that base search would automatically be restricted to those countries.

**Comment by sadatmalik** [comment]
John: this gives a way to resolve the pre-filter new searches by green-lit locations.

**Comment by sadatmalik** [comment]
This should also resolve #248

**Comment by samschlicht** [comment]
The issue here appears to be that this SavedSearchService method doesn't apply the filters contained in the base search.

![Screenshot 2024-01-12 at 1 48 15 pm](https://github.com/Talent-Catalog/talentcatalog/assets/111261894/71cd7bff-a9a0-40be-9056-1ac5a79ae042)

So, I'll take a look at the way a base search is joined to a regular search and consider how to replicate for an elastic one.

**Comment by samschlicht** [comment]
Have written the code to gather the joinSearchRequests and just reviewing the way they are combined on regular search — some learning required here in terms of Specifications and lambdas!

**Comment by samschlicht** [comment]
I've got to an interesting place: I'm iterating through joinRequests with computeElasticQuery adding keywords and filters — wrapping up for today but will do some testing tomorrow.

**Comment by samschlicht** [comment]
Leaving this for now due to impending release date and other more pressing issues. I've got something that seems to be working, which I'll push.

Before I go any further:
- [x] More manual testing
- [x] Discuss current state of play with JC

Left to do:
- [x] What about regular searches built on elasticsearch searches? (Right now this branch can handle elastic built on elastic, elastic built on regular (except incompatible fields, see below), but not regular built on elastic — it ignores the keyword search term). Either address that here or create a new issue. #677
- [x] **Missing fields**: min/max age, min/max years experience — full compatibility requires alignment #678
- [x] The joined searches have a searchType (and/or), need to check this can't vary for joined searches
(As I thought, they're always set to 'and' — all good)
- [x] Angular currently stopping Base Search input when Keyword Search has input.
- [x] There's some refactoring to be done between doSearchCandidates() and searchCandidates() - lots of duplicated code.
- [x] When/if(!) successful, make a base search for country of operations

**Comment by cazcam34** [comment]
@samschlicht Im looking at potentially doing #248, which seems to be dependant on this issue? Is it possible I could move forward with #248?

**Comment by samschlicht** [comment]
@cazcam34 once this one's done they'll be nothing to do for #248 — I'll just save a 'Countries of Operation' search and that one will be cleared too. 🙂

**Comment by samschlicht** [comment]
I've got something that's working and will review on Wednesday with John.

**Comment by cazcam34** [comment]
Oh nice! Cool I've just picked up the Intake Search :)

**Comment by samschlicht** [comment]
😎👍
