### ISSUE TITLE
Fix visibility of chats

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#463]
As a user
I should not see chats before I should

## Visibility examples
- Candidate only sees Candidate Recruiting Chat once they have passed the CVReview stage
- For example, a job creator can only chat with candidates once those candidates have been short listed (ie at the CV review stage).

**Comment by cazcam34** [comment]
Logic in auth service or cand opp service, here is an opp is it past this stage? use that to determine if display chat or not.

**Comment by cazcam34** [comment]
- [x] Create enum method in enum.ts (dupe across to cand portal) which does the Object.keys(enum).indexOf(enumName). add doc for this method.
- [x] Add documentation
- [x] Candidate portal completed
- [x] Admin portal completed
- [x] Delete candidate opp service which I added on cand portal (if no longer needed due to using exported function)
