### ISSUE TITLE
Scrolling issue - scroll only works for left pane - right pane cannot be scrolled

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#546]
See video in this post https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1704664172354269

<img width="1108" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a17be1686c5a02bde08e599dc9a0224f6f8a251d/Screen%20Shot%202024-01-08%20at%208.50.40%20am.png" alt="Screen Shot 2024-01-08 at 8.50.40 am.png" />

**Comment by cazcam34** [comment]
Option 1: Reduce the page size that is returned to only display a smaller amount (e.g. 15) that will reduce the amount on the page and reduce the need for scrolling/can see everything on the page.
Option 2: Set the details panel as fixed AND scrollable, so that when scrolling the list of jobs/searches on the admin panel, we can also keep track of the whole detail panel. See example CSS below for detail panel:
    height: 700px; (as example)
    overflow: auto;
    position: fixed;
    right: 0;

**Comment by cazcam34** [comment]
Problem with scroll bars and tables - if a table is cut off due to the scroll overflow being hidden, it isn't clear that there is more table to view. Could cause confusion. I think making the content sticky-top fixes this issue of loosing what we are looking at when scrolling... however only really works if the content in the sticky section isn't longer than the page view. If content longer it won't act sticky. We can fix this by limiting the content in the details panel by rducing the amount of candidates that appear in the submission list preview (eg. to 12) and we already have the chats component as scrollable so the candidate opps section isn't likely to be long anyways.

**Comment by cazcam34** [comment]
Problem with page size caching - we set a default page size for source results (candidate in a list) but when we view the list in full, and go back to the list in the list with detail it has cached the total page size (20) and now it shows 20 in the preview.
