### ISSUE TITLE
Demo/Video - Employer Access / Job Chats

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#566]
Better to not do this in the weekly All-Teams.

- [x] User interface TBB admin

- [x] Employer Access focussed
- [x] Source job-chats focussed
- [ ] TBB Destination job-chats focussed (job creators / non-job creators)
- [x] Candidate job-chats focussed

To follow:

- [ ] Employer (Iress) focussed - demo/video?
- [ ] 3rd party Recruiter focussed - demo/video?

**Comment by camerojo** [comment]
### Notes

- [ ] Employer access user (Iress-au, john-test) does not show Group Chats tab on job
- [x] Job Informaton typo
- [ ] Completing job intake does not check box allowing for job to be published

**Comment by camerojo** [comment]
### Videos

See folder at https://drive.google.com/drive/u/2/folders/1I65KIy4oLyzooBrPFPTH4vqt3ScQAmYZ

@sadatmalik Completed key videos as requested. Pretty rough because I ran out of time - finding some nasty bugs as I was switching logins from a single browser! Ended up confusing Stomp because it was not being reset as expected at logouts. Anyway fixed that - but that did not leave much time for videos.

Next problem was that I discovered that combining job creator, source partner and candidate job chats into a single video might be simple but the Slack video limit of 5 minutes is not quite enough. Maybe three separate videos is the way to go. Watched one after another.

Plus I need to script them better. But hopefully these will give you what you need to keep moving forward.

I also did the employer access video - but it probably needs to be redone.

**Comment by sadatmalik** [comment]
Brilliant - thanks so much John. Well done on finding (and fixing) a few gotchas!

**Comment by camerojo** [comment]
@sadatmalik After thinking about it, I think I will go with three JobChat videos - for the three user types: job creator, source partner and candidate. 

Source partner is the one to start with - because the source partner is the only one to see all 5 types of chat.

Job creator sees only 4 - they don't see the chat between just the source partner and candidate

Candidate only see the 3 types that include them (they don't see the chat between job creator and individual source partner, and between job creator and all source partners.

I will have another go at those three videos on Monday.
