### ISSUE TITLE
Add consent to participate in monitoring & evaluation projects to TC intake

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#567]

**Comment by samschlicht** [comment]
Check out the epic for context — but briefly: because the World Bank impact evaluation survey is to include unsuccessful candidates, we need to get their proactive consent, and the research team felt this was best obtained during intake. In part because that offers an opportunity briefly to explain the project, to avoid any confusion and better the chances of the person choosing to participate.

Suggest reviewing #299 which did a very similar thing for the candidate portal, and #402, which synced those new fields to SF.

Here are the broad steps:
- [ ] Add new boolean field to candidate entity (something like, 'monitoring and evaluation consent')
- [ ] Add new tab (to my eyes, this is needed — note to discuss w group) and checkbox to full intake form
- [ ] Add field to SF candidate sync code (SalesforceServiceImpl)
- [x] Add checkbox to SF candidate contact records, prod and sandbox

**Comment by samschlicht** [comment]
Noting that I've contacted Sarah to check if they have a view on how the Q should be phrased on the intake form — will add to this issue anything that comes back. I've advised they be fairly generic with the TC Q, since it would ideally continue to apply to M & E projects after the World Bank one expires.

(They plan to have some accompanying materials ready for any candidates who want to know more — an email containing FAQs and a video of a TBB alum explaining the project, and a script for the source team conducting the intake.)

**Comment by samschlicht** [comment]
@cazcam34 just a note — if you do pick this one up — that I've already added the checkbox to SF staging and prod. I needed it to move ahead with my survey automation. Let me know if you want to revise for any reason, it's not set in stone at this point, of course.

Here are the details:
Object Name: Contact
Data Type: Checkbox
Field Label: Monitoring & Evaluation Consent	
Field Name: Monitoring_Evaluation_Consent
API Name: Monitoring_Evaluation_Consent__c	 	 
Help Text: Indicates consent given at TC intake to be contacted for monitoring and evaluation projects

<img width="1332" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--695b6a22dcbaf9ee09a2abde405baee28afd9b0c/Screenshot%202024-01-18%20at%2010.45.00%E2%80%AFam.png" alt="Screenshot 2024-01-18 at 10.45.00 am.png" />

**Comment by cazcam34** [comment]
Hi @samschlicht - I'm picking this one up now :) Quick couple of questions:
1. Does this sit on both the Mini & Full Intake? Or just the Full Intake?
2. For the full intake we already have a accordion panel called "End of Intake" (see screenshot) which details some 'todos' before completing the intake. Would this accordion section be appropriate for the monitoring Q checkbox? When you say new tab do you mean new section of the accordion? 

<img width="1300" alt="Screenshot 2024-01-18 at 3 19 20 pm" src="https://github.com/Talent-Catalog/talentcatalog/assets/43192228/ccaeef14-14ee-44d7-b0ee-4ab891fc0e3d">

**Comment by samschlicht** [comment]
@cazcam34 I would imagine just the full intake, and yep, sorry, I did mean a new section of the accordion.

What do you think? My issue with the 'End of Intake' section is that doesn't have any other interactive elements, so I imagine staff are accustomed to skipping past it. I did wonder whether the whole thing should be checkboxes, but not sure we want to complicate this issue so much!

To be honest I deliberately left it open because I figured we might get a chance to discuss — I was undecided.

**Comment by cazcam34** [comment]
@samschlicht yeah we decided against checkboxes for those fields as we wouldn't really need to track the responses, so saving to the DB seemed unnecessary. We could make the complete intake button require validation to ensure that the survey question isn't skipped? Alternatively we could put the question in it's own accordion section. Orrr perhaps some of those bullet points (e.g. the verbal agreement to share profile - which seems important) should also be made into checkboxes, which would then make the section more interactive, along with the survey checkbox/dropdown. Perhaps we can discuss in our call tonight :)

**Comment by samschlicht** [comment]
Yea I'd say it merits group discussion — we still have the issue that the
'complete intake' button doesn't really do anything! This may all be up for
grabs when we do the comprehensive intake review. For now I'd say the
crucial thing is that no one skips the question, which was my concern with
putting it in that final section.

**Comment by cazcam34** [comment]
Notes from discussion on call: Put the question in the end of intake section on the full intake.

**Comment by cazcam34** [comment]
Seperate potential issue: We currently set intake dropdowns with 'NoResponse' if a previously selected value is removed (and not replaced with another answer). A value needs to be selected as we only set the fields where `data.getField` != null`, so in order to change a value we can't send a null from the front end or else that value won't get updated. This won't happen very often, but while thinking of connecting a field to Salesforce, this could potentially pose a problem? In reporting even? As we need to factor in that there may be some 'NoResponse' answers along with dropdown fields.

**Comment by cazcam34** [comment]
<img width="1591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e06bc36bdfcf30239224a688ef8c62ffdb65b25/Screenshot%202024-01-22%20at%202.03.04%20pm.png" alt="Screenshot 2024-01-22 at 2.03.04 pm.png" />
@samschlicht  I have finished the TC code to add the monitoring field to the intake as discussed and saving that to a new field on the database (monitoringEvaluationConsent - as per your SF field). The wording of the question is TBC, i just put something in for now.

I am now up to the point of populating this field over to SF, however I am a bit unsure where this will need to go. I wonder if it'll be good to wait for your Sync Tc candidates to SF PR (#402) to go in as that seems to have some good examples of other transferrable TC to SF fields? What do you think? Otherwise I may need to pick your brains about the SF code!

**Comment by cazcam34** [comment]
Some notes (also in code)
Need to set the string enum to a boolean to match the SF field (checkbox). This boolean field is then used in survey workflows. Kept the string value on the TC as we can capture Yes/No which provides a bit more detail on the response (e.g. difference between No vs NULL) but need to convert this to boolean for our SF workflow. Only explicitly answering Yes will render true. No, NoResponse & NULL values render false.
