### ISSUE TITLE
Set candidate opportunity relocating dependants from candidate opportunity

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#651]
- We're adding the ability to update SF candidate opportunity relocation information from the CA visa assessment (#161) and also expanding and refining the visa tool for other countries (#647, #646) to offer this functionality.
- But Zeynep warns that some countries may never reliably use the visa assessment tool, and in any case, family changes can happen at any time, past the point where the visa tab seems the obvious place to go to update.

Discussing this w John raised the notion that this info could be viewable and modifiable from a tab on the TC candidate case too.

**Comment by samschlicht** [comment]
Spoke to John and just adding a note that we discussed the possibility of having the relocating dependants viewable and modifiable from the visa tab and somewhere on the candidate opportunity. That way it would be accessible and logically placed irrespective of a country's visa process and the current stage of the recruitment. TBC!

**Comment by cazcam34** [comment]
We save relocating dependants on the candidate visa job check object... if we allow this field to be set via the candidate case AND a visa job check for the job hasn't yet been created we need to create one. But that then needs to be connected to a destinations visa check so one of those will also need to be created. Automating this creation of two objects from a whole other component doesn't seem quite right... 
Do we move relocating dependants field to the candidate opp? This can then easily be set via the visa job check because an opp has to be created prior to the visa job check being able to be done so nothing will need to be created. 
Will raise in tonights meeting...

**Comment by cazcam34** [comment]
As discussed with team, move the relocating dependants field to the candidate opportunity object.

**Comment by cazcam34** [comment]
- [x] Create flyway to add new field over to candidate opps table
- [x] Create SQL to move field over to new table
- [ ] Finally, delete field on old table candidate visa job check
- [x] DONT FORGET to undo local changes on camerojo computer before running flyway
- [x] Finish the updateSF button method
- [x] Get the component working on visas
- [x] Move fields and methods to candidate opportunity objects/services
- [x] Get working on candidate case
- [ ] Update the tests where I've changed the code!

**Comment by cazcam34** [comment]
When a SF update is done, we only log errors and don't return them to the front end. It will cause problems as for users it appears to have 'worked'. I've added a small error exception to this, if you're happy I can put this in a new issue.

**Comment by cazcam34** [comment]
This worked!! Safe for Prod as checked for duplicate visa job checks and there were none.
update candidate_opportunity co set relocating_dependant_ids =
    (select relocating_dependant_ids from candidate_visa_job_check cvjc
        join salesforce_job_opp jo on cvjc.job_opp_id = jo.id
        join candidate_visa_check cvc on cvjc.candidate_visa_check_id = cvc.id
        join candidate c on cvc.candidate_id = c.id
        where co.candidate_id = c.id
        and co.job_opp_id = cvjc.job_opp_id);
