### ISSUE TITLE
Do display of all candidates that source has chat with

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#693]
As a source partner
I want a display where I can see all candidates that I have opened chats with
so that I can see a notification when there a new posts from any candidate

**Comment by samschlicht** [comment]
@camerojo before diving into this there's something need to understand about the creation of candidate chats: they're auto-created when a TBB user views a candidate, but not when one of our partners does. What's the reason for that? Is it because TBB is also a destination partner?

**Comment by samschlicht** [comment]
Thanks, @camerojo, but the candidate-chat tab doesn't appear for the source partner, so how will they message them?

**Comment by samschlicht** [comment]
What I'm seeing is that a chat gets created, but the sourcePartnerId in the request is null (a detail that surprised me) and the tab doesn't appear in the candidate profile.

That's viewing as a source partner. When viewing as a TBB user, I see it.

**Comment by camerojo** [comment]
> Thanks, @camerojo, but the candidate-chat tab doesn't appear for the source partner, so how will they message them?

That candidate chat IS automatically created when a candidate becomes associated with a job opportunity. 

Currently we don't have a way of initiating the chat without an opportunity - but that is functionality we might add in future.

**Comment by samschlicht** [comment]
> > Thanks, @camerojo, but the candidate-chat tab doesn't appear for the source partner, so how will they message them?
> 
> That candidate chat IS automatically created when a candidate becomes associated with a job opportunity.
> 
> Currently we don't have a way of initiating the chat without an opportunity - but that is functionality we might add in future.

@camerojo it's being created with or without a candidate opportunity, but is only visible to a TBB user.

**Comment by samschlicht** [comment]
@camerojo how to replicate:

- breakpoint in ChatAdminApi line 107
- pick candidate without any opportunities and open full profile view
- you'll hit the breakpoint and see that a new chat has been created
- if you're a TBB admin, a tab will appear; if you're a source partner admin, it won't

**Comment by samschlicht** [comment]
I've found a couple of issues that feel like blockers for this one, documented in #1095. Since I'm on leave from tomorrow, I'm going to put this one back in the backlog for now and pick up something smaller. If it isn't taken when I get back, I'd be keen to have another go, but I leave that to fortune!

**Comment by samschlicht** [comment]
The bug mentioned above is fixed, so I'm going to push ahead with this one. 👍

**Comment by samschlicht** [comment]
@camerojo when we meet tomorrow it'd be great to discuss this one, in addition to our hot fix work - there's an interesting question about where to place it on the admin portal...

I'm actually wondering if it merits its own tab (if not now, then in time), as pictured. And perhaps it would not just gather all chats with candidates, but also have a panel containing all unread messages, and even an option to write a message re any job to any of the principals.

I'm interested to hear what Mariam says, but as an admin user I think I would want one centralised place to do my corresponding, in addition to the separate job and candidate screens.

To be clear, I'm not suggesting we do all this at once, but the longer-term view would inform where I place and how I lay out this issue's version.

FYI and input: @sadatmalik @cazcam34 @EhsanEhrari 


<img width="1853" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjNqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03ffa6649cf7c691d29b3a15e0dd692b6064b2f7/Screenshot%202024-07-16%20at%204.13.02%E2%80%AFPM.png" alt="Screenshot 2024-07-16 at 4.13.02 PM.png" />

**Comment by samschlicht** [comment]
Separately to the question of how we route to this component and whether it's part of a broader chat console, I'm not going to reinvent the wheel here.

We already have the makings of this component within the job UI, substituting job source partners with candidates that the logged in source partner manages:

<img width="1838" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBempwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed2e001cb2b3285bc915ee83444f60f5e6b16855/Screenshot%202024-07-17%20at%202.51.58%E2%80%AFPM.png" alt="Screenshot 2024-07-17 at 2.51.58 PM.png" />

I'll populate the table with all the candidates that the source partner already has chats with, and complement that with a function to create new chats with candidates who aren't yet listed.

**Comment by samschlicht** [comment]
Spoke to the team about the placement of this component and we agreed that the Chats tab is a potential epic for the future, whereas for now I'll add a '[partner] Candidate Chats' tab to the Jobs menu.

**Comment by samschlicht** [comment]
Hey @camerojo quick question on this one that would be useful to know for when I get back:

What's the criteria for the CandidateProspect chats to be displayed in this component?

- already has posts from the logged-in user
- already has posts from someone in the logged-in user's organisation 
- already has posts from any admin user, candidate is managed by the source partner (doesn't really work for TBB)

I have my own thoughts but would be great to get yours before proceeding.

**Comment by samschlicht** [comment]
Noting that TBB will have access to all the candidates with an active chats (replicating the default partner visibility they have elsewhere). That'll mean querying a lot of candidates, but we can always change it later, if necessary.

**Comment by samschlicht** [comment]
We discussed in the team meeting reusing the show-candidates component but I'm taking a look at it and I think it's overkill — there are nearly 2000 lines of code and with so much functionality and template elements that I don't need here.

Noting there's a slimmed-down candidate-source-results component that I might be able to use instead - I'll take a look and report back.

FYI @camerojo @cazcam34

**Comment by samschlicht** [comment]
Updating this note for clarity:
Reusing show-candidates.component as discussed in the team meeting was not feasible in the end — there are over 2000 lines of code, much of which would need adapting, and so much functionality that I don't need.

As an alternative, Sadat and I discussed making a separate ticket for refactoring some of this common code, making some smaller reusable components and perhaps a base class for similar components, e.g. candidate-source-results. To be discussed at a later point, particularly with @cazcam34.

**Comment by samschlicht** [comment]
@cazcam34 

Also editing here for clarity — last night's message was a bit of a brain dump!

Given I won't be reusing show-candidates.component, there's now a decision to be made about whether to still have the candidate profile card appear, rather than the current arrangement (pictured) with just the chat window on the right-hand side.

I would need to add the chat tab to the profile card (it currently isn't included) and in this case probably have the card open each time on that tab. It would be great, before I move forward again, to get your view — basically any sense you have of what's a minimum viable product to deliver this time around, and should I incorporate the card or stick with the chat window? I suppose the argument against the profile card is that we're adding more info that perhaps isn't required for the work that will be done here, and also there's the question of what to do with the empty space on the right-hand side when a candidate isn't selected! 

Any input you have would be super-useful, happy also to have a chat if you have time.

<img width="1430" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1kQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be844edf52a9fd3043769e155db7dd647cc59754/Screenshot%202024-07-30%20at%205.48.04%E2%80%AFPM.png" alt="Screenshot 2024-07-30 at 5.48.04 PM.png" />

**Comment by samschlicht** [comment]
UPDATE: I took the advice to create a minimal viable product respecting the 3-day estimate. This will give us something to refine, a starting point that at least works or (I believe) would be useful even in its present state.

I'm actually leaning toward preferring not to have the candidate card — this gives instant chat access for a slimmed down UX. If anything, the card could appear elsewhere on the screen and keep the chat console where it is, prominent and instantly accessible. But I'm happy to defer to the group and particularly @cazcam34 on that question!

This version has the following features:

- sortable columns
- auto-submitting keyword search name and id
- pagination
- unread posts notification on tab and candidate rows
- clickable icons and dropdown menu replicated from search and list screen

If this version were to be approved, there's just a bit of doc and CSS still to be done.

Possible additional features and improvements if given more time:

- date of most recent post (preferably sortable, though that would be a challenge, given it would be a transient field with paginated results)
- sort candidate rows by unread posts (again, possibly challenging, as that processing is done in the front end - would maybe have to be per page)
- some sort of date/status filter (this screen will fill up over time if there's no way to remove candidates)
- some refactoring of common code with Opportunity screens and show-candidates (and other candidate-row view components, as discussed above)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGtpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b58bdc6f73a3d99f421ebfb76b1562fdc6207a8f/Screenshot%202024-07-31%20at%204.32.42%E2%80%AFPM.png" alt="Screenshot 2024-07-31 at 4.32.42 PM.png" />

FYI @sadatmalik @camerojo

**Comment by cazcam34** [comment]
@samschlicht I think this is great! Tbh this is what I was leaning towards. What I originally was meaning when I was suggesting using the candidate search card component, was more so for a seperate issue. I thought that adding that tab to the current use of search card (in searches and lists) could be useful so that people can easily see if a candidate has chats by just viewing the tab in the search card - but when they are in a search/list view. 
But for your UI and new tab, I think just displaying the chat is perfect! I personally prefer the cleanness to it and I agree it could be overkill having the search card here.

Another small thought, additionally to this view, could we have a 'unread chats' or 'chats' list that is automatically updated? That way they can just view their list, and view the chats in that list and then they also get the search card there too.

**Comment by samschlicht** [comment]
@cazcam34 thanks for that feedback, and glad we're on the same page. If the rest of the team has no objections, in that case I'll polish up what I've got and submit PR this afternoon.

I'm seeing scope for 3 new issues here, and please chime in again if I've not quite understood this new suggestion (3).

1. Refactoring of common code between my new component and the FilteredOppsComponentBase, and between show-candidates, my component, and any similar others (I know of at least one).
2. Adding the 'Chat with Candidate' tab to the candidate profile search card.
3. An auto-updating 'unread chats' list that would offer another place to correspond but via the Chat with Candidate tab on the candidate profile search card, which already appears in the Lists screen, where this would naturally live.

The only thing I'd say about no. 3 is it'd be good to have a list of that type that wasn't only for candidates but all users and chat types (so, _all_ unread chats) — and in my mind it'd live on the as-yet hypothetical 'Chats' screen. I don't know whether that's instead-of or as-well-as, though!

**Comment by camerojo** [comment]
See my comments on the PR. For a minimal MVP I would go with a much simpler candidate list (losing some of the icons and menus - eg for downloading a CV or displaying tasks). That means a lot less code copying.

In doing that, you might end up with a simpler base component that show-candidates can subclass - ie a step towards the refactoring you were suggesting above. We don't have to do that now - but for now I think it would be good to minimize the duplication of code by displaying a simpler candidate display.
