### ISSUE TITLE
Mini Intake - Confirm General Information - Registration process changes - multiple nationalities

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#697]
See: https://www.canva.com/design/DAFtz28cQHE/JZI_5copovFN8N1fE2lQYg/view

Make it possible for candidates to add multiple nationalities they may hold as part of the registration process

**Comment by sadatmalik** [comment]
Discussed with John - agreed to implement this.

See the slide deck: "Make it possible for candidates to add multiple nationalities they may hold as part of the registration process."

**Comment by cazcam34** [comment]
<img width="1417" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZtQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bf70e0ffab5ec160f2aa34f32fab0e530f21a7d/Screen%20Shot%202024-07-02%20at%2011.55.44%20am.png" alt="Screen Shot 2024-07-02 at 11.55.44 am.png" />

**Comment by cazcam34** [comment]
Since we are just wanting to collect a nationality country (we don't need to collect other associating information e.g. Occupations which includes an occupation and a number of years in occupation) then I see the best way to do this would be making country dropdown a multiselect dropdown? And then changing the field to be a list of country ids instead of a single country id?
<img width="965" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekNtQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c23313e6003454405360c8a1bef61ef481ca0747/Screen%20Shot%202024-07-02%20at%2012.01.45%20pm.png" alt="Screen Shot 2024-07-02 at 12.01.45 pm.png" />

**Comment by EhsanEhrari** [comment]
To ensure candidates can add multiple nationalities during the registration process, modifying the country dropdown to a multi-select dropdown is a good approach. As @cazcam34 suggested, changing the candidate nationality field to a list of nationalities instead of a single nationality ID is essential. However, this change would require all relevant components to use the list of nationality IDs instead of a single nationality ID. Given these considerations, do you think this approach is feasible and beneficial for our system? Are there any potential challenges we should be aware of before proceeding?

**Comment by EhsanEhrari** [comment]
We may need to update several parts of application. This involves modifying the model, HTML form, component, and service to handle a list of country IDs instead of a single country ID.

**Comment by EhsanEhrari** [comment]
And also we may need to update any other components or parts of the application that rely on the nationality field to use nationalities.

**Comment by EhsanEhrari** [comment]
Further investigation: I found that currently, the Candidate entity has a ManyToOne relationship with Country for nationality. Since candidates can now have multiple nationalities, we may need to change this to a @OneToMany relationship and update the database schema.
We may need to update the service layer (CandidateService) to handle saving and retrieving multiple nationalities for a candidate.

**Comment by EhsanEhrari** [comment]
**Summary**
- **Backend**: We need to modify entity relationships, service methods, and API endpoints.
- **Frontend**: We need to update templates, form handling, and service integration in Angular.
- **Database**: We need to update database schema.

**Comment by EhsanEhrari** [comment]
@sadatmalik What do you think?

**Comment by cazcam34** [comment]
To discuss where this is at in meeting - discussed with @camerojo and making nationalities multiple fields will break code, we need a single nationality as it's one of the major sorts they use. What are the next steps with this ticket?

**Comment by sadatmalik** [comment]
We will review with the product team in the next intake revisions meeting (8 August)

**Comment by sadatmalik** [comment]
**Reviewed this in today's meeting with Noura, Zeynep, John and Sadat.**

We agreed to keep the current question as it is, which asks for the Country of Nationality, so the underlying data will remain as is.

Additionally, we will ask for any other nationalities, which can be added one at a time using a "+" button for each nationality - modelled on how we ask for multiple citizenships in the mini-intake.

**Comment by camerojo** [comment]
Simpler to use a multiselect "Other nationalities" if they say that they have other nationalities.

After Nationality, have simple yes/no question - "Do you have other nationalities?". This is not stored. But if they say yes, show multiselect drop down.

- [x] Main nationality (and any other nationalities) should automatically add CandidateCitizenships entries.
