### ISSUE TITLE
Mini Intake: Personal Status / Program Eligibility - intake screen changes only

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#705]
See: https://www.canva.com/design/DAFtz28cQHE/JZI_5copovFN8N1fE2lQYg/view

Implement intake screen only changes to Personal Status / Program Eligibility from the relevant slides.

**Comment by samschlicht** [comment]
REMOVAL - p14 of slide deck, remove 'Date of Asylum'
Logged on the removal ticket

**Comment by samschlicht** [comment]
I'm unclear on the request on p15 and its rationale. I've tagged Noura and Mariam in [this TC channel Slack post](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1710288578793639) for some clarification. John in 1-1 today agreed, so we'll await the response.

**Comment by samschlicht** [comment]
- [x] Changed 'Are you engaged or married?' to 'What is your marital status? Agreed w JC that this makes sense and it's done.

Not really clear what this bullet is asking for but taken on face value it's asking for us not to record partner info if they're not 'registered with TBB':
<img width="318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9734e9aeef132c8ce23b9d57cbcb47cd3251b816/Screenshot%202024-03-13%20at%204.18.18%E2%80%AFpm.png" alt="Screenshot 2024-03-13 at 4.18.18 pm.png" />

We could clarify that w Source, but I think it's connected to this request (also on p16), which is a non-starter anyway:

**- auto-populate the partner Qs if they're registered on the TC**

I get the reasoning here, but it's quite a substantive and questionable revision that I'll have to run by the team. 

As I see it, this section is an opportunity to collect _the most current information_ from _the principal candidate_. It could be useful to make the link to the partner's TC profile (as we currently do) if they have one, and notwithstanding some data protection issues it could be useful to display a summary in this section (though that's not what's being asked for). 

But I think we'd still need to ask the candidate the same questions. What if the partner's profile is out-of-date or was inaccurate/incomplete to begin with? We wouldn't know if we don't ask the questions, and then how much are we gaining by auto-populating the answers anyway? What if the partner is in a different country from the principal candidate, and subsequently the intaker doesn't have permission to see their data? That's not an issue if we're just optionally displaying it, but it could be if we're trying to auto-populate fields.

_I discussed this with John and he agrees that the data doesn't really map, and the technical challenges aren't justified by the upside._

**- make it possible to add more than one citizenship for the partner**

This seems reasonable. Additional citizenships could be important for immigration options.

_John's on board for this one, so I'll go ahead and make a plan for what remains of this ticket_.

**Comment by samschlicht** [comment]
Next steps:
- [x] Correspond w source about the things we can't do. 
(Sadat is speaking to Noura directly re this and other issues in this epic.)
- [x] Convert partner_citizenship_id to a text field with no foreign key constraints, intended to store potentially multiple countries of citizenship as a comma-separated string.
- [x] Make front-end dropdown a multi-select, allowing user to choose one or more options from all countries
- [x] Front-end to pass array of country ids, converted by server to the comma-separated string
- [x] Check that this won't affect the candidate portal 
- [x] Add arrest and imprisonment Q if approved by team

**Comment by samschlicht** [comment]
There's an issue in the data here which I've referenced in [this Slack post](https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1710397729122959):

- The dev DB candidate table's partner_citizenship_id column has a foreign key constraint linking it to Nationality, which is incorrect:
<img width="506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ec1f46fa9e495f3ff339f19102c56ea400d3fb3/Screenshot%202024-03-14%20at%205.23.06%E2%80%AFpm.png" alt="Screenshot 2024-03-14 at 5.23.06 pm.png" />

- The staging and prod DBs instead have a foreign key constraint linking that column to Country, which works:
<img width="511" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--837ba423826b09fb9a00b6a3755fc9fc3d5d2aee/Screenshot%202024-03-14%20at%205.22.34%E2%80%AFpm.png" alt="Screenshot 2024-03-14 at 5.22.34 pm.png" />

I'm deleting the foreign key constraint anyway, but just noting the issue here — it appears that some manual edits have been made to the prod and staging DBs (there's no Flyway file that made this change). 

It made the initial part of this issue quite complex: I wasn't able to save any partner citizenships because of the error produced by the erroneous foriegn key restraint. Luckily I can make a Flyway that works in both dev and prod — the constraint has the same name in both instances, but just references a different external table.
<img width="657" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5vQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3b7b5753793fadf6784b616d8887f0de2ed679f/Screenshot%202024-03-18%20at%2010.46.04%E2%80%AFam.png" alt="Screenshot 2024-03-18 at 10.46.04 am.png" />

**Comment by samschlicht** [comment]
Probably just need to check wording w team but this is how it looks
<img width="1844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f25124bfa02f35c68eb7d2f2e112785e0752f631/Screenshot%202024-03-18%20at%201.12.42%E2%80%AFpm.png" alt="Screenshot 2024-03-18 at 1.12.42 pm.png" />

**Comment by samschlicht** [comment]
Noting that Noura has replied to my question re the arrest/imprisonment Q, so maybe we do need to add that to the issue:

Noura Ismail
Hi Sam Schlicht! Sorry for the slow response - both Mariam Olleik and I were traveling for meetings last week!
Re your questions:
This is an additional question - not replacement of anything else in that category
And yes, you are definitely right - conviction of a crime is more significant for immigration purposes to the destination country overall, but it's still important to have any form of arrest/detention made clear on the intake as it can potentially impact departure from the host country (ie, may inhibit ability to obtain an exit permit to leave, etc). Crime conviction is definitely more serious but arrest is still important for us to know and overall helpful to have separate. Let me know if you need more context!


_I've adjusted the TODO list accordingly, and will run by the team_

**Comment by samschlicht** [comment]
Interesting little quirk that I can see Caroline has made use of in her code but may not be known by the whole team:
When Angular expects an array of numbers and you pass it a string of comma-separated numbers (or a single number with no comma) it will handle those as an array.
<img width="309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0688660a1c87f2a45510f558adb50e033c6a75d8/Screenshot%202024-03-18%20at%2012.50.51%E2%80%AFpm.png" alt="Screenshot 2024-03-18 at 12.50.51 pm.png" />
👆
✨
👇
<img width="396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fc93ab62f7ca8aac0abec9c0ac21e28bc52d15e/Screenshot%202024-03-18%20at%2012.51.43%E2%80%AFpm.png" alt="Screenshot 2024-03-18 at 12.51.43 pm.png" />

**Comment by samschlicht** [comment]
Have contacted John to coordinate review and merge of this one — I can't grab Flyway 301 and update that branch until I'm ready to go ahead, as it'll stop anyone else grabbing the next number and merging an up-to-date Flyways branch in to theirs (mine makes alterations to the DB and so would break their build).

For that reason I'm going to put the imprisonment/arrest Q in a separate branch!

**Comment by samschlicht** [comment]
Approved to proceed but the imprisonment Q needs to sit directly BELOW the conviction Q.

Note for me — keep using the same branch and just PR again w the new changes.
