### ISSUE TITLE
Cannot logout because logout drop down is obscured.

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#792]
See https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1711427838526249

- [x] revert the z-index settings
- [x] make the emoji window a modal on candidate portal
- [x] add margin to solve visibility issue on admin portal

**Comment by cazcam34** [comment]
Proving much harder than anticipated. It's a clash of z-indexes. I set the z-index lower than the right column component so that the emoji picker would sit above navbar. However now the navbar dropdowns sit below the right column (causing the bug). They both are fighting for the top spot! Trying to set the z-index lower down in the component (to just the emoji picker) doesn't seem to work, and the sticky position of the right column also causes issues.
Tried the idea of making the emoji picker appear at the bottom instead of the top, however this then can get cut off if there are many chats and the quill editor is ready at the bottom of the page.

**Comment by cazcam34** [comment]
Updated idea: chatted with @camerojo and for next release, change the account dropdown to an account nav item (page). This will have tabs Settings & a button for logout. 

Another option is having the modal pop out view (like emoji reactions) for the toolbar

**Comment by cazcam34** [comment]
@samschlicht I have reverted the z-index in the branch for this issue, if you have a chance and it's fresh in your mind could you apply the emoji picker as a modal in the branch. If you don't have time though don't stress I'll give it a go on Tuesday :)

**Comment by samschlicht** [comment]
I've been able just to increase the z-index of the emoji picker, so I'm curious why that didn't work before but I've submitted for PR since it appears to have solved the issue without causing any others.

<img width="934" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2tuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c3ee7d886633cec7eba546c3173df69ff9a860f/Screenshot%202024-04-02%20at%209.40.09%E2%80%AFam.png" alt="Screenshot 2024-04-02 at 9.40.09 am.png" />

**Comment by samschlicht** [comment]
I've made the candidate portal emoji picker a modal — on desktop view only there was an issue with the top of the picker being cut off, not by the navbar but the top of the entire window. Centered modal is probably better for mobile-first anyway, so I'm happy to go with that fix there.

I've made a new issue for the next release cycle to take out some of the closing and opening pickers code, since it no longer needs to be so complex, with the modals.

**Comment by samschlicht** [comment]
Back to the admin portal...

Adding a z-index of 1050 solves the problem in all views except the job and case details, where the 'sticky' position is the issue.

Briefly discussed w Caroline the option to add some padding/margin to the view-chat-posts view. I'm going to give that a go as I actually think it couldn't hurt anyway. Here's the 'before' view, with and without a post:

<img width="963" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9uQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4771ae77f661e256a022832df2f37f5027e14de/Screenshot%202024-04-02%20at%201.07.28%E2%80%AFpm.png" alt="Screenshot 2024-04-02 at 1.07.28 pm.png" />

<img width="962" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4c55cb3bc69a08b981b8bdfa4881c113d4e4591/Screenshot%202024-04-02%20at%201.06.50%E2%80%AFpm.png" alt="Screenshot 2024-04-02 at 1.06.50 pm.png" />

**Comment by samschlicht** [comment]
And after: 

<img width="964" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bc10f21022d5d3d72d02c26e7834313ca779269/Screenshot%202024-04-02%20at%201.20.38%E2%80%AFpm.png" alt="Screenshot 2024-04-02 at 1.20.38 pm.png" />

<img width="969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40c90a2ead1cf069be3224a597b004c32c19f4e3/Screenshot%202024-04-02%20at%201.20.27%E2%80%AFpm.png" alt="Screenshot 2024-04-02 at 1.20.27 pm.png" />

**Comment by samschlicht** [comment]
In all cases the emoji picker now squeaks in!
