### ISSUE TITLE
Emails not sending in Prod

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#840]
Email looks to be configured correctly:

<img width="1427" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL00zQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0c57b1346491aa4d75501e334665f76d827b237/Screenshot%202024-04-04%20at%2021.54.26.png" alt="Screenshot 2024-04-04 at 21.54.26.png" />

But sending emails is failing:

<img width="1419" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2MzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6f1e492d713ea06c165f973fc78374a1caf36e6/Screenshot%202024-04-04%20at%2021.55.42.png" alt="Screenshot 2024-04-04 at 21.55.42.png" />

**Comment by camerojo** [comment]
The issue was that the tc@talentcatalog.net account on Google GMail was not configured as accepting connections from "Less Secure Apps". (Click on security account settings). This seems to have fixed the problem.

However, this ability is soon going away: see https://support.google.com/accounts/answer/6010255?hl=en

Following the instructions in the above link, in order to move to the approved way of accessing GMail from a program like the TC, I needed to move to using a "app password" set up in the tc@talentcatalog.net Gmail account specifically for Talent Catalog. 

Once set up, that is the password that the Talent Catalog must use to log in. That password is generated by Google - you have no control over it. So I needed to change the email password on the prod TC (I also updated it on Staging, although staging email is currently disabled - STUB). That meant creating new task definitions and restarting both staging and prod.
