### ISSUE TITLE
Issue with new Users accessing New Search for the first time

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#846]
Mari Christy reported this issue:

<img width="946" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWM3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a809352137aa321014e8d56b33da7723477eca99/image.png" alt="image.png" />

She is a new user so I suspected it has something to do with that as the issue was not happening for me or any other users. Investigating further she was able to open a search that I made for her.

To workaround the issue I renamed the search (that I made for her) in the database to be a DefaultSearch for her user ID, and marked the search as default = true.

When she now opens the New Search screen this default search is loaded and the screen displays fine. I have applied the same fix for Gabriela Munoz (another new starter working with Mari)

The purpose of this ticket is to document the workaround fix - and to investigate why this issue is happening for new users (seemingly since release 2.2.1)

**Comment by samschlicht** [comment]
I was able to replicate this error by creating a new admin user.

Here's a bit more from the console:
<img width="1760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--952704bfc31f30c3c53ba3faa8d9c03522f417b6/Screenshot%202024-04-09%20at%202.11.40%E2%80%AFPM.png" alt="Screenshot 2024-04-09 at 2.11.40 PM.png" />

Apparently ([LINK](https://confluence.atlassian.com/jirakb/clientabortexception-errors-appear-in-jira-server-logs-225122378.html)), this exception can mean that the connection to the client browser was aborted before the response is fully transferred. 

Yep, it's timing out due to getting stuck in a recursive loop here (and indeed this is new code from V2.2.1):

<img width="1242" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEZFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e8b5aea59261ba40487a0bd4b1047301ac96a3e/Screenshot%202024-04-09%20at%202.37.07%E2%80%AFPM.png" alt="Screenshot 2024-04-09 at 2.37.07 PM.png" />


<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9731a27e0692a859333b4dd260baca3297187116/Screenshot%202024-04-09%20at%202.20.27%E2%80%AFPM.png" alt="Screenshot 2024-04-09 at 2.20.27 PM.png" />

**Comment by samschlicht** [comment]
- User opens 'New search' tab
- Frontend makes call to SavedSearchAdminApi GET default, which calls SavedSearchService.getDefaultSavedSearch()
- When no default search is found (because they're a brand new user), that method calls createSavedSearch(), passing a generic request.
- But createSavedSearch() calls getDefaultSavedSearch() right away — and we're stuck!

**Comment by samschlicht** [comment]
[784-displayed-columns-configuration-of-saved-search-gets-lost-when-update-search-is-clicked](https://github.com/Talent-Catalog/talentcatalog/pull/787/files) was the PR that introduced the bug while fixing another, so I need to try and eliminate the new one without reintroducing the old one.

**Comment by samschlicht** [comment]
This may not be the best solution, and as always I'm interested to get the team's view, but I've put in PR that at least works: if there is no default saved search already, getDefaultSearch() itself creates a bare-bones default search, rather than calling createSavedSearch() in the first instance.

That obviously means there's a bit of code duplication with the createSavedSearch() method (3 lines), but this was the 'light-touch' option that doesn't imperil John's previous bug fix or any other functionality.

**Comment by samschlicht** [comment]
<img width="1697" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2899216a5afd2dc60b186650da4314583b12dbbf/Screenshot%202024-04-09%20at%205.19.13%E2%80%AFPM.png" alt="Screenshot 2024-04-09 at 5.19.13 PM.png" />

**Comment by samschlicht** [comment]
<img width="645" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlpFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62d01afbd16d69e59ec54b657b088b3642460476/Screenshot%202024-04-09%20at%205.23.27%E2%80%AFPM.png" alt="Screenshot 2024-04-09 at 5.23.27 PM.png" />

**Comment by samschlicht** [comment]
Wondering if, whatever the solution, this might need to be a hot fix? 

If it's a few months till the next release, that's quite a lot of manual DB updates. Not to mention that David F adds new TBB users and wouldn't be able to do it himself. Also a messy start if we ever forget to do it for an external partner and this is their first experience.
