### ISSUE TITLE
Bug: Duplicate opportunity in List

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#927]
See also #956

From Kat:

Small bug to report I think. Somehow there are two of the same opportunity on one of <@U01BRD90GF8>’s opportunities: <https://tctalent.org/admin-portal/list/7647>

The candidate should be closed with the stage “Candidate not eligible for visa” - but when I try to close it I get the following error:

<img width="1145" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ef7b5696332bc002e7ff0e06ed5bebf6793744b/Screenshot%202024-04-29%20at%203.00.10%20PM.png" alt="Screenshot 2024-04-29 at 3.00.10 PM.png" />

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1714417256089159?thread_ts=1714417256.089159&cid=C42S4AJ73)

**Comment by cazcam34** [comment]
Tried replicating adding two of the same candidates to a list, with no luck. Digging into the database I saw that:
- the candidate only appears once in the list (candidate_saved_list) 
- but the candidate has TWO records on candidate opportunites table (same candidate id and same job id)
- They are both created at the exact same time.
- One of the candidate opps has a SF id, where as one doesn't. 
- One has a created by/updated by while the other doesnt.
- both records in the TC list link to a single same opportunity record - this is either the one with the sf_id or without. I've noticed both.

(See top two on screenshot)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmloQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6baded9a2210334a614b164b4ede3e439b5baccb/Screen%20Shot%202024-04-30%20at%2011.58.05%20am.png" alt="Screen Shot 2024-04-30 at 11.58.05 am.png" />


So do I delete one of them so that then can use the TC to update the other with the required status? Probably best to delete the one without the sf id so that it doesn't impact SF?

**Comment by cazcam34** [comment]
Note: There are 80 candidate opportunitites on the prod database that do not have an sf_if (`sf_id is null`) so don't have a matching opp on SF. Could these be old opportunities that didn't get created when added to a list?

**Comment by cazcam34** [comment]
Update! Was looking for any other opportunites that had sf_id = null, and were created around the same time as the one above (2023-11-02 just half an hour later) I found another one that was created on the same day and so I checked out that candidate's other opportunites and:
- There are ALSO two created for the one candidate for one job, one which has an sf_id and one which doesn't! So I think it is probably a bug that was in for a period of time which caused two opps to be created one with sf id and one without.
See screenshot below (this is for a candidate id of 179935 and job id 537)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c363b097f3e9abbb91e1f8a727eb7a0899f6bf99/Screen%20Shot%202024-04-30%20at%2012.21.32%20pm.png" alt="Screen Shot 2024-04-30 at 12.21.32 pm.png" />

**Comment by cazcam34** [comment]
Ran the following to find there 157 candidate opps that are duplicated for the same candidate/same job.
`SELECT candidate_id,
       job_opp_id,
       sf_id,
       created_date
FROM   (SELECT *, COUNT(*) OVER (PARTITION BY candidate_id, job_opp_id) AS cnt FROM   candidate_opportunity) co
WHERE  cnt > 1;`

A few do have sf_ids for both opps, so there is two with same candidate id and job opp id. In these cases though the created date is not the same, and these are older opps. So perhaps it was possible to have two candidate opps for same job, they were just added at different times. Anyways this is a slightly different case to what we are dealing with Kat's issue.
However same at Kat's example most (56) are duplicates which have one with an sf id & one without an sf id (as examples above) and which are created at the exact same time. All these have only occurred from the 11/7/23 to 5/11/23. Which indicates this was likely a bug and no longer occurs BUT it means there will likely be more of the problem that Kat mentioned. I added another where clause to the SQL `and sf_id is null` which gave me 58 rows. So I could delete the 58 rows where sf_id is null and they appear in a duplicate based on the query above? However some of these candidate opp objects (where sf_id is null) are referenced as the main candidate object on the TC!
See this list for an example where there are 3 sets of duplicates https://tctalent.org/admin-portal/list/6589

**Comment by cazcam34** [comment]
**For Kat's bug specifically**  fyi @camerojo 
I went to the candidate opp table, and searched by candidate_id = 181867. This candidate has three opps, but you can filter by job opp id and see the two which are for the same job 539. See screenshots below.

- Two candidate opportunities for candidate 181867 with job opp id 539.
- Ids are _7580_ & _5863_.
- Id _7580_ has an sf id (but no created by)
- Id _5863_ has no sf id (but it has a created by).
- On the TC in the submission list they both link to the cand opp 7580. This I found by looking at the list [here](https://tctalent.org/admin-portal/list/7647) and seeing where the candidate opp button takes me.

Therefore we can try an delete 5863, but maybe copy over the missing created by user from 5863 to 7580?

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99eb2cfcc3b825c810b72716add2036f9c954116/Screen%20Shot%202024-04-30%20at%207.47.05%20pm.png" alt="Screen Shot 2024-04-30 at 7.47.05 pm.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adb67043352f50aa4fb2e53e59f89c67939a1422/Screen%20Shot%202024-04-30%20at%207.47.34%20pm.png" alt="Screen Shot 2024-04-30 at 7.47.34 pm.png" />

**Comment by camerojo** [comment]
OK - here is a solution that I am not very proud of. I am sure that there is a better way of doing it with SQL but I think it works!

The first update sets createdBy from the opp without an sf_id
The second update sets updatedBy from the same opp
The delete then deletes the opp without an sf_id

I did this on production with Kat's example - and it worked OK.

To make this work on ALL the duplicates that you identified, just replace the 

id in (7580,5863)

with 

id in that clever select that you worked out - namely...
id in (SELECT id FROM (SELECT *, COUNT(*) OVER (PARTITION BY candidate_id, job_opp_id) AS cnt FROM candidate_opportunity) co WHERE cnt > 1))


update candidate_opportunity set created_by = (
    select created_by from candidate_opportunity
    where candidate_id = candidate_opportunity.candidate_id and
        job_opp_id = candidate_opportunity.job_opp_id and
        sf_id is null and created_by is not null and id in (7580,5863))
where created_by is null and (id in (7580,5863));

update candidate_opportunity set updated_by = (
    select updated_by from candidate_opportunity
    where candidate_id = candidate_opportunity.candidate_id and
        job_opp_id = candidate_opportunity.job_opp_id and
        sf_id is null and updated_by is not null and id in (7580,5863))
where updated_by is null and (id in (7580,5863));

delete from candidate_opportunity where sf_id is null and (id in (7580,5863));



If that makes sense - let's do it together @cazcam34  some time on production to clean up all the other bad data.

**Comment by camerojo** [comment]
Thinking about how this bug could happen I think there will be some code like this.

CandidateOpportunity x = new CandidateOpportunity();
:
candidateOpportunityRepository.save(x);
Some other changes to x
candidateOpportunityRepository.save(x);

What is wrong with that code is that save(x) returns a new x.

The code should be...

x = candidateOpportunityRepository.save(x);
Some other changes to x
candidateOpportunityRepository.save(x);

The first code will create two copies of x;

The second (correct) code example will create x, save it, returning a new x - then update and save that same x again.

The good news is that I have searched our current code and I can't find any example of that  - which makes me more confident that it is an old bug that has been fixed.

**Comment by cazcam34** [comment]
@camerojo  The only thing is that sometimes the object out of the two (the duplicate candidate opps) that is referenced, is the one WITHOUT the sf_id. And sometimes it references the one WITH the sf_id. 
So doing a blanket approach deleting where sf_id is null will come up with the referenced error in some cases won't it?

See this list [here](https://tctalent.org/admin-portal/list/6589) which has three sets of duplicates. Two of these duplicates link to the candidate opp WITHOUT the sf_id. 
Candidate 114840 links to cand opp 5071 (without sf_id)
Candidate 98592 links to cand opp 5121 (without sf_id)
The other duplicate links to the candidate opp WITH the sf_id. 
Candidate 19362 links to cand opp 5121 (with the sf_id)
Therefore appears to be a mix of referencing one or the other.

Kats worked because the candidate opp that was referenced was the one WITH the sf_id. So deleteing the one without the sf_id worked.

**Comment by camerojo** [comment]
Good point @cazcam34 

We would only get an delete error if we tried to delete an opp that was actually referenced by another table.
I did a search of the database definitions and the only other table that ever actually referenced candidate_opportunity was job_chat. See below. But that was subsquently changed. job_chat no longer directly references candidate_opportunity - and no other table does. So we shouldn't get an error deleting an opp.

create table job_chat
(
    id               bigserial   not null primary key,
    candidate_opp_id bigint references candidate_opportunity,


However because both opps have been displayed to users, users have been able to add extra data to which ever one they like. For example there are closing comments on opp 5121 which is an opp with no sf_id. As well as createdBy and updatedBy we need to copy across any extra data that has been added to the opps with the empty sf_id. Otherwise it will be lost.

**Comment by cazcam34** [comment]
@camerojo oh ok that's good it doesn't referenced elsewhere! I think it confused me as it's in a saved list, but it really is just the candidate that is in the list and because there are two opps for that list that's why two appear.

So next steps:
We need to copy over any fields that are missing, so basically make them exact duplicates then we should be able to delete the one without the sf_id. This will all be done via SQL or will this be best done manually?

**Comment by camerojo** [comment]
Best done with Sql given that there are quite a few

**Comment by camerojo** [comment]
This has been fixed by running the SQL referred to above. No code changes were required so I deleted the associated branch ([927](https://github.com/Talent-Catalog/talentcatalog/tree/927-bug-duplicate-opportunity-in-list))

There are still a few odd bits of data lying around but they do not need to be fixed urgently. See issue #956
