### ISSUE TITLE
Integrate SF / TC Occupations [Add new SF object for occupations mirroring TC occupations (English)]

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#93]
As a source team member
I would like to see ISCO job classifications on the SF opportunity
So that I can easily include these in TC candidate searches for that opportunity

**Comment by sadatmalik** [comment]
Opened by JC on Trello Boarrd in Dec 2022 - moving here following discussion with Zeynep -

Add new SF object for occupations mirroring TC occupations (English)

See:
https://www.ilo.org/public/english/bureau/stat/isco/

**Comment by sadatmalik** [comment]
SF consultancy?

**Comment by samschlicht** [comment]
I've tentatively gone ahead and actioned this, since nothing will break if we choose to amend.

Opted for a multi-select picklist added to employer job opportunities (some job opportunities are relevant to more than one occupation). Note tooltip, which should clarify for users: 'Select relevant ISCO occupation(s) to help source team conduct TC candidate search for this opportunity'

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c5b0f8203abb94445485217182828cf19ad8943/Screenshot%202023-10-31%20at%203.27.58%E2%80%AFpm.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--149846a6faf048cac0c115ed5db1b68a3feccb74/Screenshot%202023-10-31%20at%2012.41.22%E2%80%AFpm.png)

**Comment by samschlicht** [comment]
Would be good to get team feedback, and if agreed, will let destination teams know via Slack to start using the field.

**Comment by sadatmalik** [comment]
Sounds good. Let's pick up in the meeting tomorrow. Thanks @samschlicht

**Comment by samschlicht** [comment]
Also just noting this Q - are we happy for this object just to live in SF, or should we mirror it on the imported TC job? My assumption is we would want to do that, since many of our source partners don't have access to SF. Just wanted to check my understanding on the whole before moving forward with that.

**Comment by samschlicht** [comment]
Currently this issue is moving forward as [this](https://app.zenhub.com/workspaces/tc-engineering-646c91f0c3176e1ce584ec28/issues/gh/talent-catalog/talentcatalog/425) spike, reviewing whether we should actually make occupations a bona fide SF object.

**Comment by samschlicht** [comment]
See the spike at #425 for the resolution to this one!
