### ISSUE TITLE
Automated TC message on stage change

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#930]

**Comment by samschlicht** [comment]
Listing job chat types here for ref:
````
public enum JobChatType {
    /**
     * Participants: job source and destination partner associated with prospects for the job
     * in a particular source location
     */
    JobCreatorSourcePartner,

    /**
     * Participants: All source partners, job destination partner
     */
    JobCreatorAllSourcePartners,

    /**
     * Participants: Source partner and candidate in source location who is a prospect for the job,
     * but who has not yet reached the stage (after CV Review) where they will be communicating
     * directly with the destination partner.
     */
    CandidateProspect,

    /**
     * Participants: Source partner, destination partner and candidate in source location whom the
     * employer has expressed interest in (ie post CV Review)
     */
    CandidateRecruiting,

    /**
     * Participants: All source partners, job destination partner, all candidates who have passed a
     * certain stage (eg job offer)
     */
    AllJobCandidates`

**Comment by samschlicht** [comment]
**Job Opp**

- Candidates should receive posts about their candidate opp, not the job opp
- I think it would be useful for source partners to receive a post about the job changing stages, although I'm a little concerned about overdoing notifications. Nevertheless, I will code this one and see what the team reckons. If, for example, a job ended up closed because no suitable candidates were identified, or an employer turned out to be ineligible, it seems useful for all source partners to be notified.
- [x] JobCreatorAllSourcePartners

<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekM3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d58a71871a6bab38c9cd4c8a756c512bdc0004b1/Screenshot%202024-05-07%20at%2011.22.44%E2%80%AFAM.png" alt="Screenshot 2024-05-07 at 11.22.44 AM.png" />

<img width="1282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeSs3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa2a295a16fbadc903f4b807c041f49856d52396/Screenshot%202024-05-07%20at%2011.21.55%E2%80%AFAM.png" alt="Screenshot 2024-05-07 at 11.21.55 AM.png" />

**Comment by samschlicht** [comment]
**Candidate Opp**
This gets a bit interesting. I'll take each in turn:

- [x] JobCreatorSourcePartner - I think this one needs doing. We want the job creator to know when a particular candidate is e.g. being intaked and the source partner to know when they're e.g. being checked for visa eligibility. All the stages are potentially of interest/informative to both parties.

<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekc3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7555dcce4324b08645a76041778fbef0dd44969e/Screenshot%202024-05-07%20at%2011.23.37%E2%80%AFAM.png" alt="Screenshot 2024-05-07 at 11.23.37 AM.png" />


<img width="996" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTI3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e8936e3f9bf32e4df66b821ff469787792291a0/Screenshot%202024-05-07%20at%2011.18.47%E2%80%AFAM.png" alt="Screenshot 2024-05-07 at 11.18.47 AM.png" />


- JobCreatorAllSourcePartners - I don't think we want to broadcast candidate opp progress to source partners who don't have a connection to the candidate. The above option is more focused.
- CandidateProspect, CandidateRecruiting, AllJobCandidates - I'll run this by the team but I'm looking at the stages and I don't see much of a case for automating posts to candidates. Stages that require their input will be known to them anyway, and the others don't strike me as adding value to the candidate communication that will already be underway. I also think we need to tread carefully in terms of automation here — there's potential for an admin slip and then a misleading (and currently un-deletable) post ends up with a candidate.

**Comment by samschlicht** [comment]
I'm blocked on this one because I can't find the JobCreatorSourcePartner chat that I'm posting to. [I've posted on our Slack channel](https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1714968895962199) tagging JC for clarification.

UPDATE: it appears on the job opp, not candidate opp! JC shared [this doc](https://app.zenhub.com/workspaces/tc-engineering-646c91f0c3176e1ce584ec28/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTYzMTE0) from the ZH epic.

**Comment by samschlicht** [comment]
Noting that I'm getting an IntelliJ warning for potential NullPointerException in CandidateOpportunityServiceImpl for this condition check:

<img width="428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUsyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--627c748a7b1c5308108365e19eff85a3822fc79c/Screenshot%202024-05-06%20at%202.27.26%E2%80%AFPM.png" alt="Screenshot 2024-05-06 at 2.27.26 PM.png" />

The field is nullable but I think it will only ever be null if this a new opp creation. My code only runs if this is not a new opp creation, so I reckon I'm all good. I did a manual test, submitting an update request but leaving stage unchanged, and that was all good — the incumbent stage gets submitted in the request.
